---
- name: Install Wine on Debian
  apt:
    name: wine
    state: present
    install_recommends: true
  when: use_distro_packages | bool

- name: Set WineHQ repository and package names for Debian
  when: not (use_distro_packages | bool)
  block:
    - name: Set WineHQ stable package names fact for Debian
      set_fact:
        wine_package:
          name_64_bit: wine-stable-amd64
          name_32_bit: wine-stable
          dir: /opt/wine-stable
      when: wine_release == "stable"

    - name: Set WineHQ development package names fact for Debian
      set_fact:
        wine_package:
          name_64_bit: wine-devel-amd64
          name_32_bit: wine-devel
          dir: /opt/wine-devel
      when: wine_release == "development"

    - name: Set WineHQ staging package names fact for Debian
      set_fact:
        wine_package:
          name_64_bit: wine-staging-amd64
          name_32_bit: wine-staging
          dir: /opt/wine-staging
      when: wine_release == "staging"

    - name: Add WineHQ GPG repostiory key
      apt_key:
       url: https://dl.winehq.org/wine-builds/winehq.key
       keyring: /etc/apt/trusted.gpg.d/winehq.gpg

    - name: Add WineHQ repository
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
      register: wine_winehq_repo_debian

    - name: Update the Apt cache
      apt:
        update_cache: yes
      when: wine_winehq_repo_debian.changed
