---
- name: Set WineHQ package names and repository
  when: not (use_distro_packages | bool)
  block:
    - name: set wine-stable64 fact
      set_fact:
        wine_package:
          name: wine-stable64
          dir: /opt/wine-stable
      when: wine_release == "stable"

    - name: set wine-development64 fact
      set_fact:
        wine_package:
          name: wine-development64
          dir: /opt/wine-devel
      when: wine_release == "development"

    - name: set wine wine-staging64 fact
      set_fact:
        wine_package:
          name: wine-staging64
          dir: /opt/wine-staging
      when: wine_release == "staging"

    - name: Installing the WineHQ repository for Fedora
      become: true
      copy:
        src: winehq_fedora.repo
        dest: /etc/yum.repos.d/winehq.repo
        mode: 0644
        owner: root
        group: root
        backup: no

- name: Installing the official Wine Staging release provided by Fedora
  become: true
  dnf:
    name: wine
    state: present
  when: use_distro_packages | bool
