---
- name: Set WineHQ repository and package names for Fedora
  when: not (use_distro_packages | bool)
  block:
    - name: Set WineHQ stable package names fact for Fedora
      set_fact:
        wine_package:
          name_64_bit: wine-stable64
          name_32_bit: wine-stable.i686
          dir: /opt/wine-stable
      when: wine_release == "stable"

    - name: Set WineHQ development package names fact for Fedora
      set_fact:
        wine_package:
          name_64_bit: wine-development64
          name_32_bit: wine-devel.i686
          dir: /opt/wine-devel
      when: wine_release == "development"

    - name: Set WineHQ staging package names fact for Fedora
      set_fact:
        wine_package:
          name_64_bit: wine-staging64
          name_32_bit: wine-staging.i686
          dir: /opt/wine-staging
      when: wine_release == "staging"

    - name: Installing the WineHQ repository for Fedora
      become: true
      copy:
        src: winehq_fedora.repo
        dest: /etc/yum.repos.d/winehq.repo
        mode: 0644
        owner: root
        group: root
        backup: no

- name: Installing the official Wine Staging release provided by Fedora
  become: true
  dnf:
    name: wine
    state: present
  when: use_distro_packages | bool
